# Generated by Django 3.2.6 on 2021-11-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_picture_squashed_0005_alter_customuser_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='picture',
        ),
    ]
