# Generated by Django 3.2.8 on 2021-11-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(default="A bio hasn't been added yet.", max_length=500, verbose_name='about'),
        ),
    ]
