# Generated by Django 3.2 on 2021-10-29 05:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('cover_image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=3000)),
                ('release_date', models.DateField()),
                ('cover_image', models.ImageField(upload_to='uploads/')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='collectr_app.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=3500)),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='UserCollectsItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectr_app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectr_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectr_app.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectr_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TradeComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='comment_email', to='collectr_app.profile', to_field='email')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_trade', to='collectr_app.trade')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='comment_username', to='collectr_app.profile', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='TradeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('trade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectr_app.trade')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='attachments',
            field=models.ManyToManyField(to='collectr_app.TradeAttachment'),
        ),
        migrations.AddField(
            model_name='trade',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='collectr_app.Profile'),
        ),
        migrations.AddField(
            model_name='trade',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='trade_comments', to='collectr_app.TradeComments'),
        ),
        migrations.AddField(
            model_name='trade',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectr_app.profile'),
        ),
        migrations.AddField(
            model_name='trade',
            name='have',
            field=models.ManyToManyField(related_name='have_items', to='collectr_app.Item'),
        ),
        migrations.AddField(
            model_name='trade',
            name='want',
            field=models.ManyToManyField(related_name='want_items', to='collectr_app.Item'),
        ),
        migrations.CreateModel(
            name='ReputationFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_type', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flagged', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='collectr_app.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='collectr_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='NewItemRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=3000)),
                ('evidence', models.ImageField(upload_to='uploads/')),
                ('isActive', models.BooleanField(default=True)),
                ('new_item_name', models.CharField(max_length=100)),
                ('add_to_collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collectr_app.collection')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectr_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewCollectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=3000)),
                ('evidence', models.ImageField(upload_to='uploads/')),
                ('isActive', models.BooleanField(default=True)),
                ('new_collection_name', models.CharField(max_length=100)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectr_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemIsTraded',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offered', models.BooleanField(default=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectr_app.item')),
                ('trade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectr_app.trade')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackReviewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=3000)),
                ('evidence', models.ImageField(upload_to='uploads/')),
                ('isActive', models.BooleanField(default=True)),
                ('feedback', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='collectr_app.reputationfeedback')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectr_app.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='feedbackreviewrequest',
            constraint=models.UniqueConstraint(fields=('feedback',), name='one dispute per feedback'),
        ),
    ]
