# Generated by Django 3.2 on 2021-10-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
