# Generated by Django 3.2.6 on 2021-11-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectr_app', '0002_collection_thumbnail_squashed_0008_auto_20211107_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcollectionrequest',
            name='new_collection_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
