# Generated by Django 3.2.6 on 2021-11-07 12:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collectr_app', '0004_alter_newcollectionrequest_new_collection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcollectionrequest',
            name='new_collection_name',
        ),
        migrations.AlterField(
            model_name='item',
            name='cover_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectr_app.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectr_app.profile')),
            ],
        ),
    ]
