# Generated by Django 3.2 on 2021-11-04 14:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('collectr_app', '0004_auto_20211104_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, size=[512, 512], upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=75, size=[512, 512], upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='feedbackreviewrequest',
            name='evidence',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, size=[512, 512], upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cover_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, size=[512, 512], upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='newcollectionrequest',
            name='evidence',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, size=[512, 512], upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='newitemrequest',
            name='evidence',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, size=[512, 512], upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='tradeattachment',
            name='attachment',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, size=[512, 512], upload_to='attachments/'),
        ),
    ]
