# Generated by Django 3.2.8 on 2021-11-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectr_app', '0005_auto_20211107_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackreviewrequest',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='newcollectionrequest',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='newcollectionrequest',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='newitemrequest',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='newitemrequest',
            name='release_date',
        ),
    ]
