# Generated by Django 3.2.9 on 2021-11-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectr_app', '0006_auto_20211112_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
    ]
