# Generated by Django 3.2.8 on 2021-11-07 07:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectr_app', '0007_auto_20211107_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcollectionrequest',
            name='release_date',
        ),
        migrations.AddField(
            model_name='newitemrequest',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='newcollectionrequest',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='newitemrequest',
            name='add_to_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectr_app.collection'),
        ),
        migrations.DeleteModel(
            name='UserCollection',
        ),
    ]
