# Generated by Django 3.2 on 2022-07-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectr_app', '0007_alter_item_release_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCollection',
        ),
    ]
